# Generated by Django 2.2.2 on 2019-06-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCost', '0003_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passwordrestcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=120)),
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
