# Generated by Django 2.2.2 on 2019-06-25 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCost', '0004_passwordrestcodes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Passwordrestcodes',
        ),
    ]
